### ISSUE TITLE
opencv version required

### ISSUE THREAD

**Issue by jeong-tae** [GXYM/DRRG#12]
Some of functions are out-dated or up-to-date. Depending on which branch are you using for opencv, return values or some details may different.

very appreciate if you specify the opencv version and details you installed on your machine.

**Comment by GXYM** [comment]
> Some of functions are out-dated or up-to-date. Depending on which branch are you using for opencv, return values or some details may different.
> 
> very appreciate if you specify the opencv version and details you installed on your machine.

opencv-python  4.2
