### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by Bluelyy** [GXYM/DRRG#13]
Why only ctw1500 has an evaluation file, and other datasets have no evaluation files. How to get the evaluation of other datasets? I hope  author can reply.

**Comment by GXYM** [comment]
> Why only ctw1500 has an evaluation file, and other datasets have no evaluation files. How to get the evaluation of other datasets? I hope author can reply.

all evaluation files in dataset directory, you should check again

**Comment by Bluelyy** [comment]
But when I train, only the ctw1500 dataset can be evaluated, and the other datasets may be incomplete folder files, and the evaluation file cannot be generated after the training, so they cannot be tested.
