### ISSUE TITLE
Why the same method of training ctw1500, the recall rate is 10% lower than your result, and the accuracy rate is 5% lower. I want to improve this algorithm for graduation design, but I don’t know what to do now. 

### ISSUE THREAD

**Issue by Bluelyy** [GXYM/DRRG#15]

**Comment by GXYM** [comment]
you need to adjust the  parameter, especially threshold parameter of binarizatio. Also, you need to adjust the test image size. These factors have great influence on the performance .

**Comment by jeong-tae** [comment]
@GXYM What test size you mean? In the paper, size is specified. `In testing, we resize the shortest side to 512 if it is less than 512, and keep the longest side is not larger than 1, 024`

can you share more details to reproduce the results?
