### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/mlt2017_pretain/textsnake_vgg_100.pth'

### ISSUE THREAD

**Issue by Joneo** [GXYM/DRRG#2]

**Comment by Joneo** [comment]
Why is this a problem？

**Comment by GXYM** [comment]
> Why is this a problem？

no, it is just because there is no pretrain model. you delete the "--resume xxx"

**Comment by Joneo** [comment]
Thank you.Could you please give me the pre-training model you used? I feel that the effect of the pre-training model is much worse without it.

**Comment by GXYM** [comment]
> Thank you.Could you please give me the pre-training model you used? I feel that the effect of the pre-training model is much worse without it.

**Comment by GXYM** [comment]
you can run the script "tool/train_MLT2017.sh" and "tool/train_SynText.sh" to train the model as pretrain model. I get pretrain model by this way.

**Comment by Joneo** [comment]
thank you.I really appreciate your geneous help.
