### ISSUE TITLE
更换数剧集的问题

### ISSUE THREAD

**Issue by zsgqwer** [GXYM/DRRG#23]
train_TextGraph.py: error: argument --exp_name: invalid choice: 'Ocrtext' (choose from 'Synthtext', 'Totaltext', 'Ctw1500', 'Icdar2015', 'MLT2017', 'TD500')
在哪里添加新的数据集名称

**Comment by GXYM** [comment]
> train_TextGraph.py: error: argument --exp_name: invalid choice: 'Ocrtext' (choose from 'Synthtext', 'Totaltext', 'Ctw1500', 'Icdar2015', 'MLT2017', 'TD500')
> 在哪里添加新的数据集名称

你需要根据你的数据集存储的标注文件格式，写一个数据加载的程序，例如：/dataset/Icdar17_Text.py，这个是加载MLT-17数据的的文件，具体加载完成需要转换何种数据格式请参看dataset文件的中加载Total-Text或者MLT等数据的加载处理方式。
然后你需要在 https://github.com/GXYM/DRRG/blob/ce63248ce44aac59821ccc1b405a64953aa91b51/util/option.py#L30 里添加自己的数据名称，在训练启动文件train_TextGraph 和测试文件test_TextGraph中添加相应的调用。
