### ISSUE TITLE
Goodmorning Doctor

### ISSUE THREAD

**Issue by Huangzhizhong123** [GXYM/DRRG#24]
./vis/Ctw1500_test/1495.jpg': No such file or directory , need I put ''./data/Ctw1500/test/test_image'' into "./vis/Ctw1500/'' directory?
when i put "./data/Ctw1500/test/test_image" into ''./vis/Ctw1500/ and run the eval_TextGraph, the file of ''./vis/Ctw1500/'' will be clear. I dont know what i can do . 
 thanks

**Comment by GXYM** [comment]
> ./vis/Ctw1500_test/1495.jpg': No such file or directory , need I put ''./data/Ctw1500/test/test_image'' into "./vis/Ctw1500/'' directory?
> when i put "./data/Ctw1500/test/test_image" into ''./vis/Ctw1500/ and run the eval_TextGraph, the file of ''./vis/Ctw1500/'' will be clear. I dont know what i can do .
> thanks

In some extreme cases, no pictures will be saved, which may be caused by the poor training model. You can comment out this part in（eval.py） of the code in the corresponding part of the code to ensure the normal operation of the code。

**Comment by Huangzhizhong123** [comment]
I do pre-training our network on SynthText dataset with two epochs,then do train the model 600 epochs. finally i eval the model,but  
nothing be detected.I don't  know what i can do?

**Comment by Huangzhizhong123** [comment]
Do you have the pre_model on SynthText dataset. if you have ,please send me . i am sincere appreciation for you.
