### ISSUE TITLE
自己的数据集如何制作

### ISSUE THREAD

**Issue by S130111** [GXYM/DRRG#26]
自己的数据集如何制作

**Comment by GXYM** [comment]
你需要根据你的数据集存储的标注文件格式，写一个数据加载的程序，例如：/dataset/Icdar17_Text.py，这个是加载MLT-17数据的的文件，具体加载完成需要转换何种数据格式请参看dataset文件的中加载Total-Text或者MLT等数据的加载处理方式。只要符合要求，代码应该可以正常运行。
