### ISSUE TITLE
ICDAR2015 Dataset Format

### ISSUE THREAD

**Issue by abdur75648** [GXYM/DRRG#28]
The ICDAR2015 data downloaded from [here](https://drive.google.com/file/d/1ZWRQWJwhydoCsqdNlX80y94cKQedUywO/view?usp=sharing) is not as per the format required here.
Please provide the ICDAR2015 dataset in the format required here or at least tell the format we should use.

**Comment by GXYM** [comment]
> The ICDAR2015 data downloaded from [here](https://drive.google.com/file/d/1ZWRQWJwhydoCsqdNlX80y94cKQedUywO/view?usp=sharing) is not as per the format required here. Please provide the ICDAR2015 dataset in the format required here or at least tell the format we should use.

ICDAR2015 format :  x1,y1,x2,y2,x3,y3,x4,y4,abc
