### ISSUE TITLE
数据集链接失效哦

### ISSUE THREAD

**Issue by a-vegatable-bird** [GXYM/DRRG#32]
为什么这个数据集下载不了，那个链接网页打不开噢。

**Comment by GXYM** [comment]
> 为什么这个数据集下载不了，那个链接网页打不开噢。


可以从官方网站下载，gitHub搜索Total-Text, 就可以看到了。或者去[这里](https://github.com/GXYM/TextBPN-Plus-Plus)的谷歌云盘下载。
