### ISSUE TITLE
mlt2017 pre-train

### ISSUE THREAD

**Issue by Xiakker** [GXYM/DRRG#6]
Hello! Is it possible to pre-train using only the data of mlt2017? IC15 data is added to your code. Also, how many epochs have you pre-trained in total?

**Comment by GXYM** [comment]
> Hello! Is it possible to pre-train using only the data of mlt2017? IC15 data is added to your code. Also, how many epochs have you pre-trained in total?

yee, about 200 epochs

**Comment by Xiakker** [comment]
Ok! Thank you!!!
