### ISSUE TITLE
训练细节

### ISSUE THREAD

**Issue by Xiakker** [GXYM/DRRG#8]
您好！！！！

1. 请问 pre-train MLT17 时 参数设置为 ‘--input_size 640 --optim SGD --lr 0.01’吗？ 
2.在微调阶段 ‘ In fine-tuning,for multi-scale training, we randomly crop the text region,and resize them to 640 × 640 (batch is 8), 800 × 800 (batch is 4), and 960×960 (batch is 4), respectively’ ，不同尺寸各训多少epoch？

**Comment by bt2567** [comment]
同问，mlt17 pretrain的训练细节

**Comment by GXYM** [comment]
加载SynText的预训练（1-2个epochs），然后640 × 640 (batch is 8)训练100个epochs，在800 × 800 (batch is 4)训练100epochs， --默认使用optim SGD --lr 0.01。然后我是先测试了一下MLT数据上的效果，把测试那就轮中最好的的那一轮当作其他数据集上的预训练模型。960×960 (batch is 4)的在这个数据集上没有训练

**Comment by Xiakker** [comment]
好的，谢谢啦！我去试试。
